name: MineralContest
version: '${project.version}'
main: me.viciscat.mineralcontest.MineralContest
api-version: 1.19
commands:
  test:
    description: Testing command
    usage: /<command>
    permission: mineral-contest.testpermission
  test2:
    description: Testing command AGAIN
    usage: /<command>
    permission: mineral-contest.frickyou
  mineralcontest:
    description: Where all the things are done with this plugin
    usage: /mineralcontest <subcommand>
    permission: mineral-contest.command