name: MineralContest
version: '${version}'
main: me.viciscat.mineralcontest.MineralContest
api-version: 1.19
commands:
  test2:
    description: Testing command AGAIN
    usage: /<command>
    permission: mineral-contest.frickyou
  test3:
    description: Testing command AGAIN
    usage: /<command>
    permission: mineral-contest.frickyou2
  mineralcontest:
    description: Where all the things are done with this plugin
    aliases:
      - mcontest
    usage: /mineralcontest <subcommand>
    permission: mineral-contest.command
  arena:
    description: Teleport your team to the arena!
    aliases:
      - arene
    usage: /arena. You MUST be in a Mineral Contest game
    permission: mineral-contest.arena
permissions:
  mineral-contest.arena:
    default: true
  mineral-contest.join:
    default: true
  mineral-contest.admin:
    default: op
  mineral-contest.command:
    default: true